#!/bin/bash

# Launch different bash configuration for Linux vs OSX, interactive vs batch
#
# More info at https://github.com/gaelicWizard/bashrc_dispatch
#
# License: Public Domain.

# Configuration
# -------------
#
# BASHRC_DISPATCH_EXPORT_FUNCTIONS: export SHELL_PLATFORM and shell_is_* functions for use in other scripts.
# BASHRC_DISPATCH_PREFIX: set location for scripts to import

: "${BASHRC_DISPATCH_EXPORT_FUNCTIONS:=true}"
: "${BASHRC_DISPATCH_PREFIX:="${XDG_CONFIG_HOME:-$HOME/.config}/bash/"}"

# Code
# ----

# Avoid recursive invocation

[[ -n "${BASHRC_DISPATCH_PID:-}" && $$ -eq "$BASHRC_DISPATCH_PID" ]] && return
BASHRC_DISPATCH_PID=$$


# Setup the main shell variables and functions

if [[ "${SHELL_PLATFORM:=OTHER}" == "OTHER" ]]
then
    case "$OSTYPE" in
      *'linux'*   ) SHELL_PLATFORM='LINUX' ;;
      *'darwin'*  ) SHELL_PLATFORM='OSX' ;;
      *'freebsd'* ) SHELL_PLATFORM='BSD' ;;
      *'cygwin'*  ) SHELL_PLATFORM='CYGWIN' ;;
    esac
fi

if ! type -p shell_is_login
then
  shell_is_linux        () { false ; }
  shell_is_osx          () { false ; }
  shell_is_bsd          () { false ; }
  shell_is_cygwin       () { false ; }
  shell_is_login        () { shopt -q login_shell ; }
  shell_is_interactive  () { [[ "$-" == *'i'* ]] ; }
  shell_is_script       () { [[ "$-" != *'i'* ]] ; }

  case "$OSTYPE" in
    *'linux'*   )  shell_is_linux  () { true ; }  ;;
    *'darwin'*  )  shell_is_osx    () { true ; }  ;;
    *'freebsd'* )  shell_is_bsd    () { true ; }  ;;
    *'cygwin'*  )  shell_is_cygwin () { true ; }  ;;
  esac
fi


# Make $BASH_ENV the same in interactive and non-interactive scripts

: ${BASH_ENV:=$BASH_SOURCE} 
export BASH_ENV


# Make these available to the potentially convoluted bashrc_* startup scripts

if ${BASHRC_DISPATCH_EXPORT_FUNCTIONS:=true}
then
    typeset -rx SHELL_PLATFORM
    typeset -frx shell_is_linux
    typeset -frx shell_is_osx
    typeset -frx shell_is_bsd
    typeset -frx shell_is_cygwin
    typeset -frx shell_is_login
    typeset -frx shell_is_interactive
    typeset -frx shell_is_script
fi

# Now dispatch special files

if [[ -f "${BASHRC_DISPATCH_PREFIX}bashrc_once" && -z "${BRCD_RANONCE:-}" ]]
then
  export BRCD_RANONCE=true
  . "${BASHRC_DISPATCH_PREFIX}bashrc_once"
fi
[[ -f "${BASHRC_DISPATCH_PREFIX}bashrc_all" ]]                                   && . "${BASHRC_DISPATCH_PREFIX}bashrc_all"
[[ -f "${BASHRC_DISPATCH_PREFIX}bashrc_script" ]]      && shell_is_script        && . "${BASHRC_DISPATCH_PREFIX}bashrc_script"
[[ -f "${BASHRC_DISPATCH_PREFIX}bashrc_interactive" ]] && shell_is_interactive   && . "${BASHRC_DISPATCH_PREFIX}bashrc_interactive"
[[ -f "${BASHRC_DISPATCH_PREFIX}bashrc_login" ]]       && shell_is_login         && . "${BASHRC_DISPATCH_PREFIX}bashrc_login"


# Unset variables if necessary to avoid env polution

if ! $BASHRC_DISPATCH_EXPORT_FUNCTIONS
then
    unset SHELL_PLATFORM
    unset -f shell_is_linux
    unset -f shell_is_osx
    unset -f shell_is_bsd
    unset -f shell_is_cygwin
    unset -f shell_is_login
    unset -f shell_is_interactive
    unset -f shell_is_script
fi


# Unset local variables

unset BASHRC_DISPATCH_EXPORT_FUNCTIONS
unset BASHRC_DISPATCH_PREFIX
